### ISSUE TITLE
scRNA-seq from FASTQ?

### ISSUE THREAD

**Issue by cnk113** [phipsonlab/NextClone#3]
Hello,

This looks like a really promising package, I was wondering if it was possible to start from the FASTQs where we can define CB/UMI R1 structure for assays other than 10x and the R2 barcode structure (this looks already done based on adapter settings and such)?

Best,
Chang

**Comment by ghar1821** [comment]
Hi there,

Thank you for your interest! 

Currently it is not possible to start directly from FASTQ files. The adapters are used to find reads that are very likely to be the containing the clone barcode. Essentially, if the adapters exist in the read, chances are the sequence that is flanked by the adapter is a clone barcode.

For non 10x assays, for now, we will need to align the reads to the genome first to get a BAM file with CB/UB tags (cell barcode and UMI). Something like STARsolo may be adequate (https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md).

We're still very much actively updating the package, and introducing a feature where we can specify the CB/UMI structure (and thus have the pipeline taking FASTQ files as input rather than having to run alignment first to get a BAM file) is certainly in our radar.
